export const CREATE_RECORD_REQUEST = "CREATE_RECORD_REQUEST";
export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS";
export const CREATE_RECORD_RESET = "CREATE_RECORD_RESET";
export const CREATE_RECORD_FAIL = "CREATE_RECORD_FAIL";

export const ALL_RECORDS_REQUEST = "ALL_RECORDS_REQUEST";
export const ALL_RECORDS_SUCCESS = "ALL_RECORDS_SUCCESS";
export const ALL_RECORDS_FAIL = "ALL_RECORDS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";